const DEFAULT_TEMPLATES = [
  '{A} and {B} were mid-sentence when they realized they had the same vibe',
  '{A} pitched something wild. {B} said yes immediately',
  '{A} caught {B} staring at their outfit. No regrets',
  "{B} grabbed {A}'s arm. 'We HAVE to collaborate'",
  '{A} and {B} found a quiet corner. The conversation did not stay quiet',
  '{A} laughed so hard at {B}\'s joke they spilled their drink',
  '{B} slid their Instagram to {A}. The follow was instant',
  '{A} whispered something to {B}. {B} has not stopped smiling',
  '{A} and {B} discovered they have the exact same font opinions',
  '{B} is now {A}\'s emergency contact at this event',
  "{A} tried to explain what they do. {B} just said 'iconic'",
  '{A} and {B} were supposed to network. They made plans instead',
  '{B} convinced {A} to ditch the agenda and just vibe',
  '{A} and {B} realized they follow each other already. Awkward. Cute',
  "{A} looked at {B}'s business card and kept it",
  '{B} introduced {A} to three people in thirty seconds',
  '{A} said something profound. {B} wrote it on their phone',
  '{A} and {B} have been standing in the same spot for 12 minutes',
  '{B} spotted {A} across the room and walked straight over',
  '{A} told {B} a secret. The secret was about {B}',
  '{A} challenged {B} to a minute of silent appreciation and {B} nodded like it was the new handshake',
  "{B} made {A} promise to send the playlist that matches their pace",
  '{A} asked {B} for their hot take, and {B} answered with a metaphor no one expected',
  '{B} called {A} out for stealing the spotlight, and {A} thanked them for the accountability',
  '{A} and {B} discovered they both collect analog art books',
  "{B} kept correcting {A}'s pronunciation but then admitted they secretly loved the accent",
  '{A} drew {B} into the maker lounge just to watch them detail a prototype',
  '{B} insisted {A} try the coffee blend they created for midnight work sessions',
  '{A} and {B} created a shared mood board on their phones in under sixty seconds',
  "{B} taught {A} a breathing trick that made their espresso buzz feel manageable",
  '{A} noticed {B} sketching and asked what the shapes meant. {B} said it was their comfort zone',
  '{B} rewound {A} mid-story to highlight the fact they had the same travel mantra',
  '{A} challenged {B} to a rapid-fire question round and laughed at the unexpected answers',
  '{B} predicted {A} would be a lifelong collaborator after just two sentences',
  '{A} assured {B} their "wild idea" sounded practical once they translated it into steps',
  '{B} introduced {A} to a supply of snacks that matched their energy levels',
  '{A} and {B} synced their schedules without looking at a calendar',
  '{B} made {A} describe their dream project in emoji, then reinterpreted it as a pitch',
  '{A} lent {B} a pen that had saved every signature of serious partners',
  '{B} held up {A} as the person who truly understood the event\u2019s rhythm',
  '{A} suggested {B} run the experiment and they both agreed to share the results',
  '{B} spotted a quote on the wall that perfectly captured {A}\u2019s vibe and quoted it back',
  '{A} and {B} debated whether the soundtrack should be lo-fi or orchestral',
  '{B} told {A} their favorite podcast episode was recorded in the same city they grew up in',
  '{A} kept asking {B} about their hometown and ended up taking notes',
  '{B} let {A} into a joke only insiders understood, sealing their crew status',
  '{A} asked {B} for a quick intro to their lead designer and got a two-minute story instead',
  '{B} picked {A} as their "must-meet" person when they had one minute before the next session',
  '{A} shared a QR code, {B} scanned it, and both immediately whipped out their scribble pads',
  '{B} tested {A} on whether they could name every learning zone in under ten seconds',
  '{A} admired {B}\u2019s badges and confessed they collect them too',
  '{B} suggested turning their shared issue into a morning ritual',
  '{A} handed {B} a napkin with the outline of a future collaboration',
  '{B} told {A} they had been waiting for a voice like theirs all weekend',
  '{A} asked {B} to join a panel, and {B} slid right into "yes, when can we walk through it?"',
  '{B} promised to champion {A} during the wrap-up, no questions asked',
  '{A} teased {B} about their focus, then admitted they admired the discipline',
  '{B} offered {A} a badge swap to remember the meet-up',
  '{A} and {B} agreed to hold each other accountable for a follow-up brainstorm',
  '{B} captioned a photo of {A} with the nickname "energy architect" and {A} approved',
  '{A} invited {B} to a late-night rooftop jam that only insiders heard about',
  '{B} gifted {A} a mantra for staying curious during the next five sessions',
  '{A} and {B} found a quiet stairwell, and the silence felt like an encore',
]

export function generateStory(nameA: string, nameB: string, customTemplates?: string[]): string {
  const templates = customTemplates && customTemplates.length > 0 ? customTemplates : DEFAULT_TEMPLATES
  const template = templates[Math.floor(Math.random() * templates.length)]
  return template.replace(/\{A\}/g, `**${nameA}**`).replace(/\{B\}/g, `**${nameB}**`)
}
